sup rewrite

diff --git a/sup b/sup
--- a/sup
+++ b/sup
@@ -22,100 +22,90 @@
 # About:
 # A simple upload script for ZFH (http://zerofiles.org)
 
-# Defaults
-url_regex='^[a-z]+://.+'
+cfg_url_regex='^[a-z]+://.+'
+cfg_tmp_dir="/tmp/$USER/sup"
+cfg_script_url='http://zfh.so/upload'
 
-tmp_dir='/tmp'
-tmp_file="$tmp_dir/sup_tmp_$RANDOM"
-
-script_url='http://zfh.so/upload'
-
-default_tags='sup'
-# /Defaults
+cfg_default_tags='sup'
+cfg_default_title="Uploaded: `date +%Y.%m.%d\ at\ %H:%M:%S`"
 
 [[ -f $HOME/.suprc ]] && { source $HOME/.suprc; }
 
-usage() {
-cat << EOF
-Usage: $0 [-c title] [-t tags] [-RsF] [-D num] [file/url]
-	-c			Comment/title (deprecated, optional)
-	-t			File tags
-	-R			Set to remove file after uploading (local fs only, obviously)
-	-s			Grab a screenshot to upload instead of a file/url
-	-F			Make a fullscreen shot instead of a selected window/area
-	-D [num]	Delay the screenshot for [num] seconds
-	-h			Show this message
-EOF
+sup.msg() { echo "[sup] $1"; }
+sup.err() { sup.msg "(error) $1" >&2; }
+
+sup.usage() {
+	echo "Usage: `basename $0` [-c title] [-t tags] [-RsF] [-D num] [file/url]"
 }
 
+sup.env() {
+	for i in "$cfg_tmp_dir"; do
+		[[ -d "$i" ]] || { mkdir -p "$i"; }
+	done
+}
+
+sup.upload() {
+	[[ "$file_title" ]] || { file_title="$cfg_default_title"; }
+
+	curl -F file="@$file" \
+		-F tags="$file_tags" \
+		-F upload_mode='api' \
+		-F submit="" \
+		"$cfg_script_url" -s -L -A 'Sup Phost'
+
+	[[ "$flag_rm" ]] && { rm "$file"; }
+}
+
+sup.scrot() {
+	[[ "$scrot_exec" ]] || { scrot_exec=`which scrot`; }
+	[[ "$scrot_exec" ]] || {
+		sup.err "Please install scrot to use this function"
+		return 1
+	}
+
+	[[ "$flag_scrot_fullscreen" ]] || { scrot_args+=( '-s' ); }
+	[[ "$cfg_scrot_delay" ]] && { scrot_args+=( "-d $cfg_scrot_delay" ); }
+
+	file=`mktemp "$cfg_tmp_dir/sup_tmp_XXXXXX.png"`
+	scrot "${scrot_args[@]}" "$file"
+}
+
+sup.exclude() {
+	[[ "$2" ]] && { echo "$1"; return 1; }
+	return 0
+}
+
+sup.if_url() { echo "$1" | grep -oE "$cfg_url_regex" &>/dev/null; }
+
 while getopts "c:t:D:sFrRh" option; do
-	arg="$OPTARG"
+	case "$option" in
+		c) file_title="$OPTARG";;
+		t) file_tags="$OPTARG";;
 
-	case $option in
-		c) comment="$arg";;
-		t) tagstr="$arg";;
+		R) flag_rm='1';;
 
-#		r) set_recursive='yes';;
-		R) file_remove='yes';;
+		s) flag_scrot='1';;
+		F) flag_scrot_fullscreen='1';;
+		D) cfg_scrot_delay="$OPTARG";;
 
-		s) scn='1';;
-		F) scn_fs='1';;
-		D) scn_delay="$arg";;
-
-		h) usage; exit;;
+		h|*) sup.usage;;
 	esac
 done
 
 [[ "$OPTIND" ]] && { shift $(($OPTIND-1)); }
 
-cleanup() {
-	[[ -f "$tmp_file" ]] && {
-		rm "$tmp_file"
-	}
-}
+sup.env
 
-upload() {
-	[[ "$tagstr" ]] || { tagstr="sup"; }
-	[[ "$comment" ]] || { comment="Uploaded: `date +%Y.%m.%d\ at\ %H:%M:%S`"; }
-
-	curl -b "$HOME/.cookies" -F file="@$file" \
-		-F tags="$tagstr" \
-		-F upload_mode='api' \
-		-F submit="" \
-		"$script_url" -s -L -A 'Sup Phost'
-
-	[[ "$file_remove" ]] && { rm "$file"; }
-}
-
-check_if_url() {
-	echo "$1" | grep -oE "$url_regex" &>/dev/null && { return 0; }; return 1
-}
-
-
-trap "cleanup" EXIT
-
-[[ "$scn" ]] && {
-	scn_cmd='scrot'
-	tags="$tags, screenshot"
-
-	[[ "$scn_fs" ]] || { scn_cmd="${scn_cmd} -s"; }
-	[[ "$scn_delay" ]] && { scn_cmd="${scn_cmd} -d ${scn_delay}"; }
-
-	${scn_cmd} "${tmp_file}.png"; file="$tmp_file.png"
+[[ "$flag_scrot" ]] && {
+	sup.scrot
 } || {
-	[[ "$1" ]] || { echo "No file specified"; exit 1; }
+	sup.if_url "$1" && {
+		file=`mktemp "$cfg_tmp_dir/sup_tmp_XXXXXX"`
+		[[ "$file_title" ]] || { file_title="Source: $file; $cfg_default_title"; }
 
-	check_if_url "$1" && {
-		[[ "$comment" ]] || { comment="Source: $1, uploaded: `date +%Y.%m.%d\ at\ %H:%M:%S`"; }
-		curl -s "$1" > "$tmp_file"; file="$tmp_file"
-	} || {
-		[[ "$comment" ]] || { comment="Filename: ${1##*/}, uploaded: `date +%Y.%m.%d\ at\ %H:%M:%S`"; }
-		file="$1"
+		curl -s "$1" > "$file"
 	}
 }
 
-file_type=`file -ib "$file" | cut -d';' -f1`
-[[ "$file_type" == "text/html" ]] || [[ "$file_type" == "application/x-empty" ]] && { exit 1; }
-
-# DEBUG
-upload
+[[ "$file" ]] || { file="$1"; }
+sup.upload
